# Generated by Django 6.1 on 2026-08-18 20:05

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="showtheme",
            options={"verbose_name_plural": "show themes"},
        ),
        migrations.CreateModel(
            name="AstronomyShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=planetarium.models.astronomy_show_image_path,
                    ),
                ),
                (
                    "description_themes",
                    models.ManyToManyField(
                        related_name="astronomy_shows", to="planetarium.showtheme"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "astronomy shows",
            },
        ),
    ]
