# Generated by Django 6.1 on 2026-08-18 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_alter_showtheme_options_astronomyshow"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanetariumDome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rows",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(7),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "seats_in_row",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(7),
                            django.core.validators.MaxValueValidator(15),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "planetarium domes",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rows__gte", 7), ("rows__lte", 20)),
                        name="planetarium_dome_rows_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("seats_in_row__gte", 7), ("seats_in_row__lte", 15)
                        ),
                        name="planetarium_dome_seats_in_row_range",
                    ),
                ],
            },
        ),
    ]
