# Generated by Django 6.1 on 2026-08-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_planetariumdome"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={"ordering": ["title"], "verbose_name_plural": "astronomy shows"},
        ),
        migrations.AlterModelOptions(
            name="planetariumdome",
            options={"ordering": ["name"], "verbose_name_plural": "planetarium domes"},
        ),
        migrations.AlterModelOptions(
            name="showtheme",
            options={"ordering": ["name"], "verbose_name_plural": "show themes"},
        ),
        migrations.AddField(
            model_name="astronomyshow",
            name="duration",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.CreateModel(
            name="ShowSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_time", models.DateTimeField()),
                (
                    "astronomy_show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="planetarium.astronomyshow",
                    ),
                ),
                (
                    "planetarium_dome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="planetarium.planetariumdome",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "show sessions",
                "ordering": ["show_time"],
                "indexes": [
                    models.Index(
                        fields=["show_time"], name="planetarium_show_ti_2d077a_idx"
                    ),
                    models.Index(
                        fields=["astronomy_show", "show_time"],
                        name="planetarium_astrono_7e5570_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("planetarium_dome", "show_time"),
                        name="unique_dome_show_time",
                    )
                ],
            },
        ),
    ]
