# Generated by Django 6.1 on 2026-08-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0006_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="row",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat_in_row",
            field=models.PositiveIntegerField(),
        ),
    ]
