# Generated by Django 6.1 on 2026-08-20 19:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0007_alter_ticket_row_alter_ticket_seat_in_row"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="showsession",
            options={
                "ordering": ["show_time", "price"],
                "verbose_name_plural": "show sessions",
            },
        ),
        migrations.AddField(
            model_name="showsession",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
