# Generated by Django 6.1 on 2026-08-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
    ]
